workspace: true

stages:
- install
- test

jobs:
- name: composer
  stage: install
  image: sunasteriskrnd/php-workspace:7.4
  script:
  - composer install -d api
  cache:
  - key: vendor_$CI_BRANCH
    paths:
    - api/vendor

- name: yarn
  stage: install
  image: node:12
  script:
  - yarn
  cache:
  - key: node_modules_$CI_BRANCH
    paths:
    - web/node_modules

- name: eslint
  stage: test
  image: node:12
  script:
  - yarn --cwd web lint --quiet

- name: phpunit
  stage: test
  image: sunasteriskrnd/php-workspace:7.4
  services:
  - image: mysql:5.7
    environment:
      MYSQL_DATABASE: review_system
      MYSQL_USER: review_system
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  - redis:alpine
  environment:
    APP_ENV: testing
    DB_HOST: mysql
    DB_DATABASE: review_system
    DB_USERNAME: review_system
    DB_PASSWORD: secret
    REDIS_HOST: redis
  script:
  - cd api
  - cp .env.example .env
  - docker-php-ext-disable xdebug
  - php artisan key:generate
  - php artisan migrate
  - php artisan migrate:refresh
  - php artisan route:cache
  - composer test

- name: phpcs
  stage: test
  image: sunasteriskrnd/php-workspace:7.4
  script:
  - composer sniff -d api
