version: "2.2"

networks:
  default:
  frontend:
    name: frontend

services:
  mailhog:
    image: mailhog/mailhog
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-mailhog.rule=Host(`mailhog.${DOMAIN_SECONDARY}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-mailhog.loadbalancer.server.port=8025
    networks:
      - default
      - frontend
    mem_limit: ${MEMORY_LIMIT_MAILHOG:-200m}
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/data
    volumes:
      - ${PATH_DATA:-./data}/mailhog:/data
