version: '2.2'

services:
  mariadb:
    image: mariadb:10
    restart: always
    mem_limit: ${MYSQL_MEMORY_LIMIT:-1G}
    volumes:
      - ${PATH_DATA:-./data}/mariadb:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
