version: '2.2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    entrypoint: sh
    command:
      - -c
      - envsubst '$${DOCUMENT_ROOT}' < /etc/nginx/conf.d/default.conf.tpl | tee /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`${DOMAIN}`)
      - traefik.http.services.nginx.loadbalancer.server.port=80
    environment:
      - DOCUMENT_ROOT=${NGINX_DOCUMENT_ROOT:-/php/public}
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf.tpl:ro
    volumes_from:
      - php

  php:
    image: sunasteriskrnd/php-workspace:7.4
    restart: always
    mem_limit: ${MEMORY_LIMIT_PHP_FPM:-1G}
    working_dir: /php
    volumes:
      - ${PATH_PHP}:/php
      - ${HOSTS_FILE}:/etc/hosts
