version: '2.2'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${DOMAIN_SECONDARY}`)
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
    environment:
      - PMA_HOSTS=mysql,mysql-test
      - PMA_PORT=3306
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
